### ISSUE TITLE
Unit Definition of Input File

### ISSUE THREAD

**Issue by sebastianohl** [metalpen1984/MiniLSM#1]
Hi,

I am trying to create my own input file for the implementation. However, there is no definition which units are nessecary in the CSV file. Can you please state which units the values are required and paste an example file?

Thank you

**Comment by hydrogencl** [comment]
Hi, thanks for showing the interesting to this experimental work. 
Here is the example:

Unit: K, Pa, kg/kg, m/s, W/m^2, mm

#TBOT	PRES	QBOT	WIND	FSDS	PREC
281.8232	95141	0.00901	7.2162	0	0
281.7107	95147	0.00886	6.1447	0	0
281.8743	95146	0.00912	7.291	0	0
282.1158	95178	0.0092	7.3901	0	0
282.0438	95170	0.00927	6.1064	0	2.4
282.1601	95151	0.0094	3.9616	0	0.9
282.5096	95169	0.00956	3.623	0	1.2
282.6155	95190	0.00963	3.8819	0.58358	0.6
282.5967	95211	0.00972	4.7982	12.228	0.6
282.9796	95230	0.00977	5.1369	29.683	0.4
283.1028	95228	0.00987	4.101	56.584	0.2
